# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_auto_20160115_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AccountUser'),
        ),
    ]
