# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountuser',
            table=None,
        ),
    ]
