# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20151228_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=2),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='gym',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
