# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160227_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='gym',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
