# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 06:39
from __future__ import unicode_literals

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160227_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=apps.accounts.models.upload_to),
        ),
    ]
