# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accountuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
