# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160227_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
