# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20160227_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountuser',
            old_name='profile_picture',
            new_name='avatar',
        ),
    ]
