# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='routine',
            name='days',
            field=models.ManyToManyField(to='workouts.DaysOfWeek'),
        ),
    ]
