# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_auto_20160110_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.DateField(),
        ),
    ]
