# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_auto_20160111_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
