# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_auto_20160112_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
