# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0015_auto_20160318_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='progress',
        ),
        migrations.AddField(
            model_name='progress',
            name='sets',
            field=models.ManyToManyField(to='workouts.Set'),
        ),
    ]
