# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0016_auto_20160318_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='sets',
        ),
        migrations.AddField(
            model_name='set',
            name='progress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workouts.Progress'),
            preserve_default=False,
        ),
    ]
