# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20160107_1636'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MuscleGroup',
            new_name='ExerciseCategory',
        ),
        migrations.AlterModelOptions(
            name='exercisecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Exercise Categories'},
        ),
    ]
