# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_equitment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equitment',
            new_name='Equipment',
        ),
    ]
