# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_auto_20160107_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.ExerciseCategory')),
                ('equipment', models.ManyToManyField(blank=True, to='exercises.Equipment')),
                ('muscles', models.ManyToManyField(blank=True, to='exercises.Muscle', verbose_name='Primary muscles')),
                ('muscles_secondary', models.ManyToManyField(blank=True, related_name='secondary_muscles', to='exercises.Muscle', verbose_name='Secondary muscles')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
