# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.ExerciseCategory'),
        ),
    ]
