# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_auto_20160108_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_cardio',
            field=models.BooleanField(default=False),
        ),
    ]
