# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0013_auto_20160128_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
