# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 07:17
from __future__ import unicode_literals

import apps.exercises.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0014_exercise_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.exercises.models.upload_to)),
                ('is_main', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Exercise')),
            ],
            options={
                'ordering': ['-is_main', 'id'],
            },
        ),
    ]
