# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0016_auto_20160223_0222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciseimage',
            options={'ordering': ['-is_main', 'id'], 'verbose_name_plural': 'Exercise Images'},
        ),
    ]
