# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0018_auto_20160224_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_machine',
            field=models.BooleanField(default=False),
        ),
    ]
