# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 02:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_auto_20151228_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricTypeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='metrictype',
            name='group',
            field=models.ForeignKey(default=datetime.datetime(2015, 12, 28, 2, 56, 45, 204259, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='metrics.MetricTypeGroup', to_field='name'),
            preserve_default=False,
        ),
    ]
