# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_auto_20151230_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrictype',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.MetricTypeGroup'),
        ),
    ]
