# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_exercise_is_cardio'),
    ]

    operations = [
        migrations.AddField(
            model_name='muscle',
            name='latin_name',
            field=models.CharField(default='', help_text='Latin representation', max_length=50),
        ),
        migrations.AlterField(
            model_name='muscle',
            name='name',
            field=models.CharField(help_text='Muscle name e.g biceps', max_length=50),
        ),
    ]
