# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_auto_20160111_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muscle',
            name='name',
            field=models.CharField(blank=True, help_text='Muscle name e.g biceps', max_length=50),
        ),
    ]
