# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20160110_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
