# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_progress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DaysOfWeek',
            new_name='DayOfWeek',
        ),
    ]
