# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_auto_20160110_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='days',
            field=models.ManyToManyField(null=True, to='workouts.DayOfWeek'),
        ),
    ]
