# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_auto_20160111_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='Sets',
        ),
        migrations.AddField(
            model_name='progress',
            name='sets',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='reps',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
