# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0011_auto_20160111_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayofweek',
            name='day',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
